In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import os
from PIL import Image
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True

In [2]:
dataset=tf.data.TFRecordDataset("/home/ma-user/work/cai.tfrecords")
def _parse(data):
    feature = {
                'label': tf.io.FixedLenFeature([], tf.int64),
                'img_raw' : tf.io.FixedLenFeature([], tf.string),
        }
    res=tf.io.parse_single_example(data,feature)
    return res
dataset2=dataset.map(_parse,num_parallel_calls=tf.data.experimental.AUTOTUNE)

img_list=[]
label=[]

for data in dataset2:
    img = tf.io.decode_raw(data['img_raw'], tf.uint8)
    #print(img.shape)
    img = tf.reshape(img,[256,256,3])
    img = tf.cast(img,dtype="float64")
    #print(data["label"])
    if data["label"]==2 or data["label"]==3:
        label.append(data["label"])
        img_list.append(img.numpy())
    else:
        pass
label=np.array(label)
img_list=np.array(img_list)

In [5]:
model = tf.keras.Sequential()
#卷积1
model.add(tf.keras.layers.Conv2D(8,(4,4),kernel_initializer="he_normal",activation="relu",strides=2,padding="same",input_shape=[256,256,3]))
#卷积2
model.add(tf.keras.layers.Conv2D(16,(4,4),kernel_initializer="he_normal",activation="relu",strides=2,padding="same",name="conv2"))
#卷积3
model.add(tf.keras.layers.Conv2D(32,(7,7),kernel_initializer="he_normal",activation="relu",strides=2,padding="same",name="conv3"))
model.add(tf.keras.layers.MaxPooling2D(pool_size=1,strides=1,padding='SAME'))
model.add(tf.keras.layers.BatchNormalization())
#卷积4
model.add(tf.keras.layers.Conv2D(16,(4,4),kernel_initializer="he_normal",activation="relu",strides=2,padding="same",name="conv4"))
#卷积4
model.add(tf.keras.layers.Conv2D(16,(4,4),kernel_initializer="he_normal",activation="relu",strides=2,padding="same",name="conv5"))
"""
#卷积4
model.add(tf.keras.layers.Conv2D(16,(5,5),kernel_initializer="he_normal",activation="relu",strides=2,padding="same",name="conv6"))
model.add(tf.keras.layers.MaxPooling2D(pool_size=1,strides=1,padding='SAME'))
model.add(tf.keras.layers.BatchNormalization())"""


#droput层
model.add(tf.keras.layers.Flatten(name="flatten"))
model.add(tf.keras.layers.Dropout(rate=0.2,name="d3"))
#输出层
model.add(tf.keras.layers.Dense(4,activation="relu"))
model.add(tf.keras.layers.Dense(4,activation="relu"))
model.add(tf.keras.layers.Dense(4,activation="softmax"))
#模型编译
model.compile(loss="sparse_categorical_crossentropy",optimizer=tf.keras.optimizers.Adam(0.001),metrics=["accuracy"])

In [4]:
""""path="/home/ma-user/work/untitled的副本/
classes={
    "baoyu","daiyu","haishen","haizhe","hexia",
    "huahali","huangshan","jidan","jirou","jiweixia",
    "jiyu","lianyu","liyu","niurou","qingyu","shanbei",
    "yangrou","yarou","youyu","zhangyu","zhurou"
        }
label=[]

img_list=[]


for index,name in enumerate(classes):
    class_path=path+name+"/"
    for img_name in os.listdir(class_path):
        img_path=class_path+img_name
        img=Image.open(img_path)
        img=img.resize((256,256))
        img=np.array(img)
        #print(index,np.shape(img))
        
        if img.shape!=(256,256,3):
            pass
        else:
            label.append(index)
            img_list.append(img)
            
label=np.array(label)
"""

'"path="/home/ma-user/work/untitled的副本/\nclasses={\n    "baoyu","daiyu","haishen","haizhe","hexia",\n    "huahali","huangshan","jidan","jirou","jiweixia",\n    "jiyu","lianyu","liyu","niurou","qingyu","shanbei",\n    "yangrou","yarou","youyu","zhangyu","zhurou"\n        }\nlabel=[]\n\nimg_list=[]\n\n\nfor index,name in enumerate(classes):\n    class_path=path+name+"/"\n    for img_name in os.listdir(class_path):\n        img_path=class_path+img_name\n        img=Image.open(img_path)\n        img=img.resize((256,256))\n        img=np.array(img)\n        #print(index,np.shape(img))\n        \n        if img.shape!=(256,256,3):\n            pass\n        else:\n            label.append(index)\n            img_list.append(img)\n            \nlabel=np.array(label)\n'

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1.

NameError: name 'model' is not defined

In [6]:
model.fit(img_list,label,verbose=1,batch_size=50,epochs=10,validation_split=0.1,shuffle=True)

Train on 1751 samples, validate on 195 samples
Epoch 1/10
1751/1751 [==============================] - 3s 1ms/sample - loss: nan - accuracy: 0.0000e+00 - val_loss: nan - val_accuracy: 0.0000e+00
Epoch 2/10
 750/1751 [===========>..................] - ETA: 0s - loss: nan - accuracy: 0.0000e+00

KeyboardInterrupt: 

In [16]:
fillname="H:/人工智能算法学习/tensorflow/vegetable_model.h5"
model.save(fillname)